CREATE OR REPLACE FUNCTION insert_verification_code(
    p_app_user_id UUID,
    p_code VARCHAR(6),
    p_verification_type VARCHAR(10)
)
RETURNS UUID AS $$
DECLARE
    v_verification_code_id UUID;
BEGIN
    UPDATE verification_code
    SET is_used = true
    WHERE app_user_id = p_app_user_id
    AND verification_type = p_verification_type
    AND is_used = false;

    INSERT INTO verification_code (
        app_user_id,
        code,
        verification_type, 
        expires_at
    ) VALUES (
        p_app_user_id,
        p_code,
        p_verification_type,
        NOW() + INTERVAL '30 minutes'
    )
    RETURNING verification_code_id INTO v_verification_code_id;

    RETURN v_verification_code_id;

EXCEPTION
    WHEN foreign_key_violation THEN
        RAISE EXCEPTION 'User not found';
    WHEN OTHERS THEN
        RAISE EXCEPTION 'Error inserting verification code: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION insert_verification_code(UUID, VARCHAR, VARCHAR) IS 
    'Inserts a verification code generated by the backend. 
    Automatically invalidates previous unused codes of the same type.
    Code expires in 1 hour (set by table default).';