CREATE TABLE IF NOT EXISTS sector(
	sector_id SERIAL PRIMARY KEY,
	sector_name VARCHAR(25) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
