CREATE TABLE IF NOT EXISTS role(
	role_id SERIAL PRIMARY KEY,
	role_name VARCHAR(25) NOT NULL,
	role_hierarchy SMALLINT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
